# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 884b2d4e1685a13435c61e388c1bdec06d4193416bc0cf87125f369cdd5107aec4d827f8b82bc490ac942648c242f880936110ba34aafb4846624d56a53540d9

test:
  secret_key_base: b868e5e0a8c19c7e4b991f8408dd25a8db983b6bddc1297bfb6ef0445bfde482e62235d5de2ea14250412e756c539c9c9e5fea8d5e9626f232a124b9570e4a1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
